@startuml
set namespaceSeparator ::

class "foodzilla::database::database.dart::SqlDb" {
  {static} -Database? _db
  +dynamic db
  +dynamic initializeDb()
  -dynamic _onUpgrade()
  -dynamic _onCreate()
  +dynamic readData()
  +dynamic insertData()
  +dynamic updateData()
  +dynamic deleteData()
  +dynamic dropTable()
  +dynamic isEmailAlreadyExists()
  +dynamic isUsernameExists()
  +dynamic showDatabaseTables()
  +dynamic checkPassword()
  +dynamic getDatabasePath()
  +dynamic getTableIds()
  +dynamic getRecommendedMeal()
  +dynamic getAllMeals()
  +dynamic getFoodDetailsList()
  +dynamic getRestaurantDetailsList()
  +dynamic getAddressByUsername()
  +dynamic getMobileByUsername()
  +dynamic getFoodDetailsListByRestaurantId()
  +dynamic searchMealsByName()
  +dynamic searchRestaurantsByName()
}

"foodzilla::database::database.dart::SqlDb" o-- "sqflite_common::sqlite_api.dart::Database"

class "foodzilla::main.dart::FoodZilla" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "foodzilla::main.dart::FoodZilla"

class "foodzilla::pages::checkout::checkoutPage.dart::CheckoutPage" {
  +List<Food> confirmationList
  +num totalPrice
  +SqlDb db
  +String userName
  +dynamic getAdd()
  +Widget build()
}

"foodzilla::pages::checkout::checkoutPage.dart::CheckoutPage" o-- "foodzilla::database::database.dart::SqlDb"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "foodzilla::pages::checkout::checkoutPage.dart::CheckoutPage"

class "foodzilla::pages::mainmenu::Landing.dart::LandingPage" {
  +String userName
  +State<LandingPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "foodzilla::pages::mainmenu::Landing.dart::LandingPage"

class "foodzilla::pages::mainmenu::Landing.dart::_LandingPageState" {
  -TextEditingController _searchController
  +SqlDb db
  +dynamic getid()
  +Widget build()
}

"foodzilla::pages::mainmenu::Landing.dart::_LandingPageState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"foodzilla::pages::mainmenu::Landing.dart::_LandingPageState" o-- "foodzilla::database::database.dart::SqlDb"
"flutter::src::widgets::framework.dart::State" <|-- "foodzilla::pages::mainmenu::Landing.dart::_LandingPageState"

class "foodzilla::pages::mainmenu::models::food.dart::Food" {
  +Uint8List? imageBytes
  +String desc
  +String name
  +String restName
  +num score
  +num price
  +num quantity
  +bool highlight
}

"foodzilla::pages::mainmenu::models::food.dart::Food" o-- "dart::typed_data::Uint8List"

class "foodzilla::pages::mainmenu::models::restaurant.dart::Restaurant" {
  +int restId
  +Uint8List? imageBytes
  +String restName
}

"foodzilla::pages::mainmenu::models::restaurant.dart::Restaurant" o-- "dart::typed_data::Uint8List"

class "foodzilla::pages::mainmenu::widgets::checkout_item.dart::CheckoutItem" {
  +Food checkoutItem
  +Widget build()
}

"foodzilla::pages::mainmenu::widgets::checkout_item.dart::CheckoutItem" o-- "foodzilla::pages::mainmenu::models::food.dart::Food"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "foodzilla::pages::mainmenu::widgets::checkout_item.dart::CheckoutItem"

class "foodzilla::pages::mainmenu::widgets::checkout_list.dart::CheckoutList" {
  +int totalPrice
  +List<Food> checkoutList
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "foodzilla::pages::mainmenu::widgets::checkout_list.dart::CheckoutList"

class "foodzilla::pages::mainmenu::widgets::food_item.dart::FoodItem" {
  +Food foodItem
  {static} +num totalPrice
  {static} +List<Food> checkoutList
  +SnackBar snackBar
  +Widget build()
}

"foodzilla::pages::mainmenu::widgets::food_item.dart::FoodItem" o-- "foodzilla::pages::mainmenu::models::food.dart::Food"
"foodzilla::pages::mainmenu::widgets::food_item.dart::FoodItem" o-- "flutter::src::material::snack_bar.dart::SnackBar"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "foodzilla::pages::mainmenu::widgets::food_item.dart::FoodItem"

class "foodzilla::pages::mainmenu::widgets::food_list.dart::FoodList" {
  +int totalPrice
  +dynamic foodListFuture
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "foodzilla::pages::mainmenu::widgets::food_list.dart::FoodList"

class "foodzilla::pages::mainmenu::widgets::home_page_title.dart::HomePageTitle" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "foodzilla::pages::mainmenu::widgets::home_page_title.dart::HomePageTitle"

class "foodzilla::pages::mealsPage::mealsPage.dart::MealsPage" {
  +String id
  +SqlDb db
  +dynamic getRecommid()
  +dynamic getAllid()
  +Widget build()
}

"foodzilla::pages::mealsPage::mealsPage.dart::MealsPage" o-- "foodzilla::database::database.dart::SqlDb"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "foodzilla::pages::mealsPage::mealsPage.dart::MealsPage"

class "foodzilla::pages::onboarding::logInPage.dart::LoginPage" {
  +TextEditingController loginUserNameController
  +TextEditingController loginPasswordController
  +Widget build()
  +void loginLogicFunction()
}

"foodzilla::pages::onboarding::logInPage.dart::LoginPage" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "foodzilla::pages::onboarding::logInPage.dart::LoginPage"

class "foodzilla::pages::onboarding::signUpPage.dart::SignupPage" {
  +TextEditingController siginUserNameController
  +TextEditingController signPasswordController
  +TextEditingController signConfPasswordController
  +TextEditingController signEmailController
  +TextEditingController signMobileController
  +TextEditingController signAddrsController
  +Widget build()
  +void normalDialogueShow()
  +void signUpLogicFunction()
}

"foodzilla::pages::onboarding::signUpPage.dart::SignupPage" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "foodzilla::pages::onboarding::signUpPage.dart::SignupPage"

class "foodzilla::pages::restaurantsPage::restaurentPage.dart::RestaurantsPage" {
  +SqlDb db
  +dynamic getRestsId()
  +Widget build()
}

"foodzilla::pages::restaurantsPage::restaurentPage.dart::RestaurantsPage" o-- "foodzilla::database::database.dart::SqlDb"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "foodzilla::pages::restaurantsPage::restaurentPage.dart::RestaurantsPage"

class "foodzilla::pages::restaurantsPage::widgets::restaurant_item.dart::RestaurantITem" {
  +SqlDb db
  +Restaurant restItem
  {static} +List<Food> checkoutList
  +Widget build()
}

"foodzilla::pages::restaurantsPage::widgets::restaurant_item.dart::RestaurantITem" o-- "foodzilla::database::database.dart::SqlDb"
"foodzilla::pages::restaurantsPage::widgets::restaurant_item.dart::RestaurantITem" o-- "foodzilla::pages::mainmenu::models::restaurant.dart::Restaurant"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "foodzilla::pages::restaurantsPage::widgets::restaurant_item.dart::RestaurantITem"

class "foodzilla::pages::restaurantsPage::widgets::restaurant_list.dart::RestaurantList" {
  +int totalPrice
  +dynamic restListFuture
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "foodzilla::pages::restaurantsPage::widgets::restaurant_list.dart::RestaurantList"

class "foodzilla::pages::searchResultsPage::searchResultsPage.dart::SearchResultsPage" {
  +String searchQuery
  +SqlDb db
  +Widget build()
}

"foodzilla::pages::searchResultsPage::searchResultsPage.dart::SearchResultsPage" o-- "foodzilla::database::database.dart::SqlDb"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "foodzilla::pages::searchResultsPage::searchResultsPage.dart::SearchResultsPage"

class "foodzilla::pages::splash::splashPage.dart::SplashBody" {
  +State<SplashBody> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "foodzilla::pages::splash::splashPage.dart::SplashBody"

class "foodzilla::pages::splash::splashPage.dart::_SplashBodyState" {
  +AnimationController? animationController
  +Animation<double>? fadingAnimation
  +void initState()
  +void dispose()
  +Widget build()
  +void goToNextView()
}

"foodzilla::pages::splash::splashPage.dart::_SplashBodyState" o-- "flutter::src::animation::animation_controller.dart::AnimationController"
"foodzilla::pages::splash::splashPage.dart::_SplashBodyState" o-- "flutter::src::animation::animation.dart::Animation<double>"
"flutter::src::widgets::framework.dart::State" <|-- "foodzilla::pages::splash::splashPage.dart::_SplashBodyState"
"flutter::src::widgets::ticker_provider.dart::SingleTickerProviderStateMixin" <|-- "foodzilla::pages::splash::splashPage.dart::_SplashBodyState"


@enduml
